name: build-lint
on: [push, pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - run: go build .
      - run: go vet .
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: golangci-lint run
       