name: build-lint
on: [push]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - run: go build cmd/main.go
      - run: go vet ./...
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0
      - run: bin/golangci-lint run --skip-dirs opt/ --skip-dirs go/
       