name: build-lint
on: [push, pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - run: go build cmd/
      - run: go vet cmd/
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0
      - run: bin/golangci-lint run
       