name: build-lint
on: [push, pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - run: go test github.com/Olin-Hydro/mother-nature/tests